services:
  app:
    build: .   # Cela indique à Docker Compose de construire l'image à partir du Dockerfile dans le répertoire courant
    container_name: app
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cleanconnect
    restart: unless-stopped

volumes:
  mongodb_data: